task default: %w[slides]

task slides: ['clean', 'slides.html', 'active_record.uml.png', 'data_mapper.uml.png']

task :clean do
  %x[rm -f *.html]
end

rule '.html' => ['.md'] do |t|
  require 'erb'
  template = File.read('slides.html.erb')
  File.open(t.name, 'w') do |file|
    BODY = File.read(t.source)
    TITLE = BODY.lines.find{ |line| line =~ /^#+\s*/ }.chomp.sub(/^#+\s*/, '')
    file.write(ERB.new(template).result(binding))
  end
end

rule '.png' => ['.ditaa'] do |t|
  %x[ditaa -E #{t.source} #{t.name}]
end
